name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run destroy against'
        type: environment
        required: true
  push:
#    branches:
#      - 'dev_*'

env:
  ENVIRONMENT: ${{ vars.ENVIRONMENT }}
  RUNNER: ${{ vars.RUNNER }}
jobs:
  deployment:
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          echo ${{ vars.ENVIRONMENT }}
          echo ${{ vars.RUNNER }}
