name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run destroy against'
        type: environment
        required: true
env:
  ENVIRONMENT: ${{ vars.ENVIRONMENT }}
  RUNNER: ${{ vars.RUNNER }}
jobs:
  deployment:
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on:
      - ${{ env.RUNNER }}
    steps:
      - name: deploy
        run: |
          echo ${{ vars.ENVIRONMENT }}
