name: Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run destroy against'
        type: environment
        required: true
env:
  ENVIRONMENT: ${{ vars.ENVIRONMENT }}
jobs:
  deployment:
    runs-on: [ ubuntu-latest, ${{ vars.RUNNER }} ]
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: deploy
        run: |
          echo ${{ vars.ENVIRONMENT }}
